"""Scope-to-agent router for chat messages.

Maps ``ChatScopeKind`` values (``session``, ``bom-entry``,
``digital-twin-node``, etc.) to the appropriate domain agent factory so
that incoming chat messages are dispatched to the right specialist.

Usage::

    from api_gateway.chat.agent_router import default_router

    agent = default_router.get_agent(
        scope_kind="session",
        twin=twin,
        mcp_bridge=mcp,
        session_id=uuid4(),
    )
    if agent is not None:
        result = await agent.run_task(request)
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any
from uuid import UUID

import structlog

from observability.tracing import get_tracer

logger = structlog.get_logger(__name__)
tracer = get_tracer("api_gateway.chat.agent_router")

# Type alias for agent factory callables.
# A factory receives (twin, mcp_bridge, session_id) and returns an agent instance.
AgentFactory = Callable[..., Any]


class AgentRouter:
    """Route chat scope kinds to domain agent factories.

    The router maintains a mapping from scope kind strings to factory
    callables.  When ``get_agent`` is called the router looks up the
    factory, invokes it with the supplied dependencies, and returns the
    resulting agent instance.  If no factory is registered for the
    requested scope kind the method returns ``None``.

    New agent factories can be registered at runtime via
    :meth:`register`, making the router extensible as new domain agents
    are added in later phases.
    """

    def __init__(self) -> None:
        self._factories: dict[str, AgentFactory] = {}

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def register(self, scope_kind: str, factory: AgentFactory) -> None:
        """Register an agent factory for *scope_kind*.

        Parameters
        ----------
        scope_kind:
            The chat scope kind (e.g. ``"session"``, ``"bom-entry"``).
        factory:
            A callable ``(twin, mcp_bridge, session_id) -> agent``.
        """
        logger.debug(
            "agent_factory_registered",
            scope_kind=scope_kind,
        )
        self._factories[scope_kind] = factory

    def get_agent(
        self,
        scope_kind: str,
        twin: Any,
        mcp_bridge: Any,
        session_id: UUID | None = None,
    ) -> Any | None:
        """Return an agent instance for *scope_kind*, or ``None``.

        Parameters
        ----------
        scope_kind:
            The chat scope kind to resolve.
        twin:
            The ``TwinAPI`` instance to inject into the agent.
        mcp_bridge:
            The ``McpBridge`` instance to inject into the agent.
        session_id:
            Optional session UUID. A new UUID is generated by the agent
            if not provided.

        Returns
        -------
        Any | None
            An agent instance if a factory is registered, otherwise ``None``.
        """
        with tracer.start_as_current_span("agent_router.get_agent") as span:
            span.set_attribute("scope_kind", scope_kind)

            factory = self._factories.get(scope_kind)
            if factory is None:
                logger.debug(
                    "no_agent_for_scope",
                    scope_kind=scope_kind,
                )
                span.set_attribute("agent_resolved", False)
                return None

            kwargs: dict[str, Any] = {
                "twin": twin,
                "mcp": mcp_bridge,
            }
            if session_id is not None:
                kwargs["session_id"] = session_id

            agent = factory(**kwargs)

            logger.info(
                "agent_resolved",
                scope_kind=scope_kind,
                agent_type=type(agent).__name__,
            )
            span.set_attribute("agent_resolved", True)
            span.set_attribute("agent_type", type(agent).__name__)

            return agent


# ---------------------------------------------------------------------------
# Default router with Phase-1 mappings
# ---------------------------------------------------------------------------


def _build_default_router() -> AgentRouter:
    """Create the default router with all current scope-to-agent mappings.

    In Phase 1 only the MechanicalAgent exists, so ``session``,
    ``bom-entry``, and ``digital-twin-node`` all route to it.
    ``approval`` and ``project`` are reserved for future agents.
    """
    from domain_agents.mechanical.agent import MechanicalAgent

    router = AgentRouter()
    router.register("session", MechanicalAgent)
    router.register("bom-entry", MechanicalAgent)
    router.register("digital-twin-node", MechanicalAgent)
    router.register("project", MechanicalAgent)
    # "approval" is intentionally unmapped (future phases)
    return router


default_router: AgentRouter = _build_default_router()

__all__ = [
    "AgentFactory",
    "AgentRouter",
    "default_router",
]
